name: ci-test

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with: 
        go-version: ^1.13
      id: go

    - name: Checkout code into the Go module
      uses: actions/checkout@v2

    - name: Test
      run: make test