name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: simple_bank
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

        
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with: 
          go-version: ^1.13
        id: go

      - name: Checkout code into the Go module
        uses: actions/checkout@v2

      - name: Test
        run: make test